config/routes.rb
Rails.application.routes.draw do
    resources :users
  resources :restaurants 
   match 'signup', to: 'users#signup', via: [:get, :post]
  root :to => "locations#index"
  resources :sessions, only: [:new, :create, :destroy]
  resources :bookings
  resources :locations
  resources :restaurants do
  resources :bookings
  end

  resources :users do
  resources :bookings
  end

   resources :categories do
    resources :restaurants
  end

end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant
	validates :date, presence: true


	validate :availability, on: :create

	private
		def availability
			#restaurant
			#start_time
			#party_size
			unless restaurant.available?(party_size, start_time)
				errors.add(:start_time, "Booking is unavilable at that time, please try another.")
			end
		end

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :restaurants
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :restaurant
  geocoded_by :restaurant_location
  after_validation :geocode, :if => :restaurant_location_changed?
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
	has_many :bookings
	belongs_to :category
	validates :name, presence: true
	validates :email, presence: true, uniqueness: true
	has_secure_password
	has_many :users, through: :bookings
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?

	def available?(party_size, start_time)
		booked = bookings.where(start_time: start_time).sum(:party_size)
		party_size <= capacity
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
	validates :name, presence: true
	validates :email, presence: true, uniqueness: true
	has_secure_password
	has_many :bookings
	has_many :restaurants, through: :bookings 
	geocoded_by :ip_address
	after_validation :geocode, :if => :ip_address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :exception
  private

  def current_user
    (@current_user||= User.find(session[:user_id]) if session[:user_id])  
  end

  def current_restaurant
    (@current_restaurant||= Restaurant.find(session[:restaurant_id]) if session[:restaurant_id])
  end

  helper_method :current_user
   helper_method :current_restaurant

   def ensure_user_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

      def ensure_restaurant_logged_in
    unless current_restaurant
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

  


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    before_filter :ensure_logged_in, only: [:create, :destroy]

def index
	@bookings = Booking.all


end

    def new
    	@restaurant = Restaurant.find(params[:restaurant_id])
    	@booking = Booking.new
    end


	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@booking = @restaurant.bookings.build(booking_params)
			@booking.user = current_user
			if @booking.save
				redirect_to user_bookings_path(@booking), notice: 'Table booked successfully!'
			else
				
				render :new, notice: 'That time is unavailable, please pick a new time.'
			end
	end

	

	
	def update 
		@booking = Booking.find(params[:id])
		if @booking.update_attributes(booking_params)
			redirect_to root_path
		else
			render 'bookings/show'
		end
	end 

	def edit
		@booking = Booking.find(params[:id])
	end

	def destroy
        @booking = Booking.find(params[:id])
        @booking.destroy
        redirect_to bookings_path
    end

	private
  	def booking_params
  	 	params.require(:booking).permit(:user_id, :party_size, :star_time, :date, :restaurant_id, :restaurant_name)
  	 end

  	


  

  	

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
def index
  		@restaurants = Restaurant.all
   	 	@categories = Category.all
	end

	def show
  		@category = Category.find(params[:id])
  		
  		if params[:search].present?
			@locations = Location.near(params[:search], 50, :order => :distance)
		else
			@locations = Location.all
		end
 	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	def index
		if params[:search].present?
			@location = Location.near(params[:search], 50, :order => :distance)

		else
			@locations = Location.all
		end
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant= Restaurant.new(restaurant_params)
			if @restaurant.save
				redirect_to root_path
			else
				render :new
			end
	end

def index

  if params[:search].present?
    @locations = Restaurant.near(params[:search], 15, :order => "distance ASC", :units => "km")
  else
    @locations = Restaurant.all
  end
end

	def show
		@restaurant = Restaurant.find(params[:id])
		if current_restaurant
            @booking = @restaurant.bookings.build
        end
	end

	def update 
		@restaurant = Restaurant.find(params[:id])
		if @restaurant.update_attributes(restaurant_params)
			redirect_to restaurant_path(@restaurant)
		else
			render :edit
		end
	end 

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	private
  	def restaurant_params
  	 	params.require(:restaurant).permit( :email, :password, :password_confirmation, :name, :avatar, :address, :avatar, :category_id, :capacity)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
    end

    def create

        user = User.find_by_email(params[:email]) 
        restaurant = Restaurant.find_by_email(params[:email]) 
        if user != nil && restaurant ==nil
        	if user && user.authenticate(params[:password])
            	session[:user_id] = user.id
            	redirect_to root_path, :notice => "Logged in!"
       	 	else
            	flash.now[:alert] = "Invalid email or password"
            	render "new"
        	end
        else restaurant !=nil && user == nil
        	if restaurant && restaurant.authenticate(params[:password])
                session[:restaurant_id] = restaurant.id
                redirect_to root_path, :notice => "Logged in!"
       	 	else
                flash.now[:alert] = "Invalid email or password"
                render "new"
        	end
        end
    end

    def destroy

        session[:user_id] = nil
        session[:restaurant_id] = nil

        redirect_to users_url, notice: "Logged out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
  if params[:search].present?
    @locations = Restaurant.near(params[:search], 10, :order => "distance ASC", :units => "km")
  else
    @locations = Restaurant.all
  end
	end

	def new
		@user = User.new 
	end

	def create
		@user= User.new(user_params)
		if @user.save
			redirect_to user_path(@user)
		else
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def update 
		@user=User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to user_path(@user)
		else
			render :edit
		end
	end 

	def edit
		@user = User.find(params[:id])
	end

	private
  	def user_params
  	 	params.require(:user).permit(:email, :password, :password_confirmation, :name, :avatar)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/rest_sessions_helper.rb
module RestSessionsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/index.html.erb
<% if current_user %>
	
		<h2> My Bookings </h2>
		<% @bookings.each do |booking| %>
  			<% if booking.user != nil %>
  			<p>Restaurant: <%=booking.restaurant.name%></p>
       			<p> Booking for: <%= booking.user.name %></p>
  				<p> Email: <%= booking.user.email %></p>
				<div class = "subject"> Date:</div> <%= booking.date %> 
			    <div class = "subject"> Time:</div> <%= booking.start_time %> 
			    <div class = "subject"> Size:</div>  <%= booking.party_size %>
			    <%= link_to "Delete", booking, :method => :delete %>
    		<%end%>
  



    	<%end%>
   <%else current_restaurant%>
   <p>Bookings for <%= @restaurant.name %></p>

            <% @restaurant.bookings.order("created_at desc").each do |booking| %>
                <% if booking.user != nil %>
                    <p> Booking for: <%= booking.user.name %></p>
                    <p> Email: <%= booking.user.email %></p>
                <% end %>
                <div class = "subject"> Date:</div> <%= booking.date %> 
                <div class = "subject"> Time:</div> <%= booking.start_time %> 
                <div class = "subject"> Size:</div>  <%= booking.party_size %>
            <%end%>
    <%end%>

app/views/bookings/new.html.erb
<h1>Book a Table</h1>
<% if current_user %>
    <%= form_for ([@restaurant, @booking]) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> booking could not be made:</h2>

     
      <% @booking.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
     
    </div>
  <% end %>

        <div class="field">
            <%= f.label :date %>
            <%= f.date_select :date %>
        </div>
        <div class="field">
            <%= f.label :start_time %>
            <%= f.time_select :start_time, {ampm: true, minute_step: 30} %>
        </div>
        <div class="field">
            <%= f.label :party_size %>
            <%= f.text_field :party_size %>
        </div>
        <%= f.submit %>
    <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
<% end %>

app/views/bookings/show.html.erb
<% if current_user %>
		<h2> My Bookings </h2>
		<% @bookings.user.each do |booking| %>
  			<% if @booking.user != nil %>
       			<p> Booking for: <%= booking.user.name %></p>
  				<p> Email: <%= booking.user.email %></p>
				<div class = "subject"> Date:</div> <%= booking.user.date %> 
			    <div class = "subject"> Time:</div> <%= booking.user.start_time %> 
			    <div class = "subject"> Size:</div>  <%= booking.user.party_size %>
    		<%end%>
    	<%end%>

<% else current_restaurant %>
		<h2> My Bookings </h2>
		<% @restaurant.bookings.order("created_at desc").each do |booking| %>
       		<p> Booking for: <%= booking.name %></p>
  			<p> Email: <%= booking.email %></p>
			<div class = "subject"> Date:</div> <%=booking.date %> 
			<div class = "subject"> Time:</div> <%= booking.start_time %> 
			<div class = "subject"> Size:</div>  <%= booking.party_size %>
    	<%end%>

<%end%>

app/views/categories/index.html.erb
<h1> Categories</h1>


<div class ="categories">
	<% @categories.order("name asc").each do |category| %>
		<%= link_to category.name, "/categories/#{category.id}" %><br> 
	<%end%>
</div>

app/views/categories/show.html.erb
<h1> <%= @category.name %></h1>
<div class="gridwrapper">





	<% @category.restaurants.order("created_at desc").each do |restaurant| %>
		<div class="tile">
			<div class="tileinner">
				<%= link_to image_tag(restaurant.avatar), restaurant_path(restaurant) %>
				<%=restaurant.name%>
				<%= link_to "Book a table:",  new_restaurant_booking_path(restaurant) %>
			</div>
		</div>
	<%end%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeatyourselfApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="headwrapper">

<img class ="logo" src="https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xpa1/v/t1.0-9/10418278_10152619923250342_3040869094789336455_n.jpg?oh=8bd0d3b1f2cac903a8d1821152be031e&oe=5489A2EB&__gda__=1420014845_6574f7936320a8f513e436487eaa600e">

<div class="title">
Seat Yo' Self
</div>
        <div class="userinfo">


            <% if current_user %>
                Signed in as <%= current_user.email %>. | <%= link_to "Profile", current_user %> | <%= link_to "My Bookings", user_bookings_path(current_user) %>  | <%= link_to "Log out", session_path('current'), :method => :delete %>
            
            <% elsif current_restaurant %>
            Signed in as <%= current_restaurant.email %>. | <%= link_to "Profile", current_restaurant %> | <%= link_to "My Bookings", restaurant_bookings_path(current_restaurant) %>  | <%= link_to "Log out", session_path('current'), :method => :delete %>
            <% else %>
                <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", signup_path %>
            <% end %>
        </div>
            
            <div class ="nav">
                <%= link_to "HOME", "/" %>   <%= link_to "RESTAURANTS", categories_path %> 
            </div>
   
        <%= form_tag restaurants_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Nearby", :name => nil %>
  </p>
<% end %>

  <%= form_tag users_path, :method => :get do %>
  <p>
    <%= submit_tag "Or by current location", :name => nil %>
  </p>
<% end %>
    </div>







<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<%= yield %>

</body>
</html>

app/views/locations/show.html.erb
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>

app/views/restaurants/edit.html.erb
<h1> Edit Restaurant Profile </h1>
<%= form_for (@restaurant) do |f| %>

<%= f.hidden_field :kind, :value => "restaurant" %>

    <div class="field">
        <%= f.label :category%><br/>
        <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true  %>
    </div>

    <div class="field">
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </div>

     <div class="field">
        <%= f.label :address %><br/>
        <%= f.text_field :address %>
    </div>

     <div class="field">
        <%= f.label :capacity %><br/>
        <%= f.text_field :capacity %>
    </div>

    <div class="field">
        <%= f.label :email %><br/>
        <%= f.text_field :email %>
    </div>
    <div class="field">
        <%= f.label :password %><br/>
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %><br/>
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
        <%= f.label :avatar %><br/>
        <%= f.file_field :avatar %>
    </div>
    <div class="actions"><%= submit_tag "Save" %></div>
<% end %>

app/views/restaurants/index.html.erb
<%@locations.each do |location|%>
<%=location.name%>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{location.latitude}%2C#{location.longitude}" %>
<%end%>

app/views/restaurants/new.html.erb
<h1>Edit Profile</h1>

<%= form_for (@restaurant) do |f| %>
<%= f.hidden_field :kind, :value => "restaurant" %>

    <div class="field">
        <%= f.label :category%><br/>
        <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true  %>
    </div>

    <div class="field">
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </div>

     <div class="field">
        <%= f.label :address %><br/>
        <%= f.text_field :adress %>
    </div>

     <div class="field">
        <%= f.label :capacity %><br/>
        <%= f.text_field :capacity %>
    </div>

    <div class="field">
        <%= f.label :email %><br/>
        <%= f.text_field :email %>
    </div>
    <div class="field">
        <%= f.label :password %><br/>
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %><br/>
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
        <%= f.label :avatar %><br/>
        <%= f.file_field :avatar %>
    </div>
    <div class="actions"><%= submit_tag "Save" %></div>
<% end %>

app/views/restaurants/show.html.erb
<h1> Profile </h1>


<div class="profile">
    <%if current_user%>

        
            <h2> <%= @restaurant.name %> </h2><br>
            <div class ="profile_info">
            <div class = "subject"> Name:</div>  <%= @restaurant.name %> <br>
            <div class = "subject"> Category:</div>  <%= @restaurant.category.name %> <br>
            <div class = "subject"> Email:</div>  <%= @restaurant.email %> <br>
            <div class = "subject"> Location:</div>  <%= @restaurant.address %> <br>
            <div class = "subject"> Size:</div>  <%= @restaurant.capacity %> <br>
            <%= link_to "Book", new_restaurant_booking_path(@restaurant) %> 
            <div class ="profile_img">
             <div class = "subject"> Image: </div> <img src= "<%= @restaurant.avatar %>"> 
             </div>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@restaurant.latitude}%2C#{@restaurant.longitude}" %>

            <div class = "subject"> Book:</div>  <%= @restaurant.capacity %> <br>

        
    
    <% else current_restaurant%>
    
            <%= link_to "Edit", edit_restaurant_path(@restaurant) %>
            <div class ="profile_info"> 
            
                <div class = "subject"> Email:</div>  <%= current_restaurant.email %> <br>
                <div class = "subject"> Location:</div>  <%= current_restaurant.address %> <br>
                <div class = "subject"> Size:</div>  <%= current_restaurant.capacity %> <br>
            </div>


           	<div class ="profile_img">
                <div class = "subject"> Image: </div> <img src= "<%= current_restaurant.avatar %>"> 
           	</div>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@current_restaurant.latitude}%2C#{@current_restaurant.longitude}" %>

<%end%>
</div>

app/views/users/edit.html.erb
<h1> Edit Profile </h1>

<%= form_for (@user) do |f| %>

<%= f.hidden_field :kind, :value => "user" %>

  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <div class="field">
    <%= f.label :avatar%><br/>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions"><%= submit_tag "Save" %></div>
<% end %>

app/views/users/index.html.erb
<%@locations.each do |location|%>
<%=location.name%>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{location.latitude}%2C#{location.longitude}" %>
<%end%>

app/views/users/my_bookings.html.erb
<h1> My Bookings </h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for (@user) do |f| %>
    <%= f.hidden_field :kind, :value => "user" %>

    <div class="field">
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :email %><br/>
        <%= f.text_field :email %>
    </div>
    <div class="field">
        <%= f.label :password %><br/>
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %><br/>
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
        <%= f.label :avatar%><br/>
        <%= f.file_field :avatar %>
    </div>
<div class="actions"><%= submit_tag "Save" %></div>
<% end %>

app/views/users/show.html.erb
<h1> Profile </h1>
<%= link_to "Edit", edit_user_path(@user) %> 

<div class="profile">
    <% if current_user %>
        <div class ="profile_info">
    	   <div class = "subject"> Email:</div>  <%= current_user.email %> <br>

       	<div class ="profile_img">
            <div class = "subject"> Image: </div> <img src= "<%= current_user.avatar %>"> 
       	</div>
    <% end %>
</div>

app/views/users/signup.html.erb
<p> Would you like to sign up as a user or a restaurant owner?</p>
<p> I'm a <%= link_to "diner", new_user_path %>, Yo! </p>

<p> Please, I own my own <%= link_to "Restaurant",  new_restaurant_path %>